backend:
  name: git-gateway
  # repo: mengting1010/ai-docsy # Path to your Github repository
  branch: master # Branch to update

media_folder: "themes/docsy/images" # Media files will be stored here
public_folder: "images" # The src attribute for uploaded media
local_backend: true

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/recipe
    label: "Post" # Used in the UI
    folder: "content/en/docs/Examples" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link Title", name: "linkTitle", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}